name: Lint

on: [push]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10']
    steps:
      - name: Checkout to triggered branch
        uses: actions/checkout@v2
        with:
          ref: ''

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint